### ISSUE TITLE
not work with crosswalk webview

### ISSUE THREAD

**Issue by zyf0330** [erperejildo/cordova-plugin-preview-camera#3]
As title, it doesn't work with crosswalk webview on Android, but I have not found anything useful to solve it.

**Comment by erperejildo** [comment]
I haven't got too much knowledge about this, sorry. This repository was created to work with Meteor (BTW, I'm going to add this to the README file).
You could try creating another issue in the main repository here:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues

**Comment by erperejildo** [comment]
If you work with Meteor you can type `meteor add crosswalk`.
Sorry if you don't, but this version of this plugin would be more related with this.
