### ISSUE TITLE
A problem exists on iOS

### ISSUE THREAD

**Issue by zyf0330** [erperejildo/cordova-plugin-preview-camera#4]
When `startCamera` in which `toBack` set to false on iOS, preview box appears behind the webpage. It happens when call `startCamera` first time after startup. And if you reload page or stop and restart camera, it becomes normal.

**Comment by erperejildo** [comment]
In the original repository you've got this info about this:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

> When setting the toBack to TRUE, remember to add the style bellow on your app's HTML body element:
> 
> style="background-color='transparent'"

Further info:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/79

BTW, this repository is just for Android (so far).

**Comment by erperejildo** [comment]
Tell me if this doesn't work to reopen ticket

**Comment by erperejildo** [comment]
Further info:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/79

**Comment by zyf0330** [comment]
It doesn't work. In fact, just the first time preview box hides behind webpage. After reload it is ok.
So it is a problem about iOS native.

**Comment by erperejildo** [comment]
Mmmm... I think I couldn't help here. So far as I said I'm working with Android. Maybe the best way would be open an issue on main repository. Despite of the fact is not under maintenance any longer its community is bigger and someone could have the same problem using iOS.
Sorry mate.
BTW, I'd appreciated your solution here if you are able to fixe it

**Comment by zyf0330** [comment]
It is ok, thanks.
